name: Run Bot

on:
  schedule:
    - cron: 0 16 * * * # at 16PM-UTC, 1AM-JST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      TZ: "Asia/Tokyo"
    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote set-url origin "https://eggplants:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git checkout main
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Run Bot
        id: run-bot
        run: |
          date
          res="$(crb -n 5)"
          status="$?"
          echo "$res" | grep -vE "^# " >> ./.log.jsonl
          echo "::set-output name=STATUS::${status}"
      - name: Commit
        run: |
          git add ./.log.jsonl
          git commit -m "update: $(date +%y%m%d)"
          git push origin main
      - name: Exit
        run: (exit ${{ steps.run-bot.outputs.STATUS }})
